### ISSUE TITLE
Add on does not work TBird 68.9.0

### ISSUE THREAD

**Issue by jmccuneprGH** [mganss/EmojiAddIn#32] opened 2020-06-21 16:21 UTC
Emoji add-on icon failed to appear in the compose message toolbar with latest update to Thunderbird - 68.9.0 - running on Windows 10 Pro.

Visiting the add-on site for Emoji reveals a download choice that is marked as incompatible.

Downloading the file found at the Thunderbird add-on site yields a file which cannot be installed by the Install From File dialog. 

https://addons.thunderbird.net/en-US/thunderbird/addon/emojiaddin/

**Comment by mganss** [comment] 2020-06-22 10:25
Strange. It says 

> Works with Thunderbird 68.0 - *

at the URL above and I can confirm that it works in 68.9.0. Can you post a screenshot of the add-on's page as it shows in TB?
Perhaps the add-on is already installed and just not visible in the toolbar? Please check if it's in the View menu.

**Comment by jmccuneprGH** [comment] 2020-06-22 10:56
OK, yes, odd. This time when I uninstalled and then reinstalled the add-on from the TBird add-ons window the installation worked correctly, TBird has been restarted, the add-on appears to be enabled as expected.

However, I no longer find a button / icon / menu item in the compose window to add an emoji to a new message (and there never was a sidebar in the compose window as noted in your add-on description.) Also, the add-on doesn't appear in the right-click menu when right-clicking within the compose window. 

Attached should be a screenshot showing the add-on and the compose window for a new message.

![Emoji-screenshot](https://user-images.githubusercontent.com/67235364/85279909-30abb280-b455-11ea-9c44-f5a402d745b4.jpg)
.

**Comment by mganss** [comment] 2020-06-22 11:23
Is there no Emoji menu item in the View menu of the compose window?

**Comment by arnauden** [comment] 2020-06-23 22:03
Hello,

I use Thunderbird 68.9.0 **32 bits** at home, and 68.9.0 **64 bits** at work, Emoji menu appears correctly in TB 68.9.0 **32 bits** compose window, but doesn't appear in TB 68.9.0 **64 bits** compose window. I hope this can help, I'm sad since I've upgraded to Thunderbird 68.9.0 **64 bits** at work and Emoji menu doesn't appear anymore :-(

Best regards,
Arnaud

**Comment by mganss** [comment] 2020-06-24 08:48
@arnauden The add-on works for me in both TB 32bit and 64bit. I doubt that this a 32 vs 64 bits issue. Have you checked the View menu of the compose window?

**Comment by jmccuneprGH** [comment] 2020-06-24 10:15
OK, yes, on my Win10Pro-64 bit machine the add-on **does** appear in the menu under View and works normally. 

In previous versions of Thunderbird it was not necessary to find the add-on as a **sub**menu item -- it appeared in the Compose window as a menu item.

**Comment by mganss** [comment] 2020-06-24 10:32
You can easily add the missing button to the toolbar by right-clicking on the toolbar (or selecting Customize from the View -> Toolbars menu) and then dragging the Emoji button from the window that opens to the toolbar. The icon graphics for the Emoji button might not show in the Customize window so you might have to drag the label that says "Emoji". Here's more about toolbar customization in TB: http://kb.mozillazine.org/Toolbar_customization_-_Thunderbird

**Comment by arnauden** [comment] 2020-06-24 16:25
Hello mganss and jmccuneprGH,

I thank both of you for your answers, I just noticed this afternoon that it was possible to add the Emoji button to the compose window by customizing the toolbar, I wasn't curious enough to try before ;-) At home, the Emoji button appeared in the compose window right after installing the addon in Thunderbird 68.9.0 32 bits, so when the behavior was different in Thunderbird 68.9.0 64 bits, I thought there was a problem with the 64 bits version of Thunderbird.

mganss,

I really thank you for your job, Emoji addon adds life to e-mails, thanks a lot ! :-D

**Comment by jmccuneprGH** [comment] 2020-06-24 17:01
OK, yes, on my Win10Pro-64 bit machine the add-on **does** appear in the menu under View and works normally. 

In previous versions of Thunderbird it was not necessary to find the add-on as a **sub**menu item -- it appeared in the Compose window as a menu item. 

> 
> 
> You can easily add the missing button to the toolbar by right-clicking on the toolbar (or selecting Customize from the View -> Toolbars menu) and then dragging the Emoji button from the window that opens to the toolbar. The icon graphics for the Emoji button might not show in the Customize window so you might have to drag the label that says "Emoji". Here's more about toolbar customization in TB: http://kb.mozillazine.org/Toolbar_customization_-_Thunderbird

OK, yes, thank you. That works. FYI in the Emoji add-on sidebar which opens, the emoji category selection icons do not correctly render on my machine. See screen shot:

![compose-emoji](https://user-images.githubusercontent.com/67235364/85541251-d4c46380-b5e5-11ea-96f9-494e093138b6.PNG)

**Comment by mganss** [comment] 2020-06-25 15:16
@jmccuneprGH Odd. I can't reproduce this issue. The category icons use a web font packaged with the add-on (unlike the emoji icons themselves which are images). Perhaps there is another add-on or a setting in TB that overrides the font?

**Comment by mganss** [comment] 2020-08-26 15:43
Closing this. Please open a separate issue for the category icons issue.

**Closed by mganss** 2020-08-26 15:43 UTC
