### ISSUE TITLE
Emoji 1.91.8 don't work with TB 102.0

### ISSUE THREAD

**Issue by Lidgeu** [mganss/EmojiAddIn#56] opened 2022-07-03 18:31 UTC
TB 32 bit on Windows 7 Home Premium 64bit

Beside issue #55 (which could be a Mozilla bad design choice), I have a big problem : your addin do not work anymore.

All your smileys are appearing (far less "friendly" as earlier) in the new TB panel BUT, when I click on an Emoji, nothing happen. 
I mean the selected smiley do not appears at the cursor point and no message, warning, notice ...

I was using your AddIn since long. It was still working with the previous TB (91.10.0) then ... bang.
Looks like the copy/paste did not work anymore.

Did I miss something ?? 
I  currently deactivated Emoji, should I delete it OR is there somewhere a parameter to change ?

**Comment by mganss** [comment] 2022-07-04 10:07
Duplicate of #52

**Closed by mganss** 2022-07-04 10:07 UTC
Labels: duplicate
